/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

int main(void)
{
    RCC_AHB1ENR volatile *const pClkCtrlReg   = ADDR_AHB1ENR;
    GPIOx_MODER volatile *const pPortDModeRed = ADDR_GPIOx_MODER ;
    GPIOX_ODR   volatile *const pPortDOutRed  = ADDR_GPIOX_ODR;
    // enable portD
    pClkCtrlReg   ->GPIOD_EN = CLOCK_ENABLE;
    // chonj che do model;
    pPortDModeRed ->pin_12 = MOD_CONF_OUTP;
    // set pin_12 high
    pPortDOutRed  -> pin_12 = PIN_STATE_HIGH;
    // 10 model
    pPortDModeRed ->pin_12 = MOD_CPNF_INPUT;
    pPortDModeRed ->pin_12 = ANALOG_MOD;
    while (1)
    {

    }


}

