/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	 uint32_t *pClkCtrRed = (uint32_t*)0x40023830;
	 uint32_t *pPortAModeRed = (uint32_t*)0x40020000;
	 uint32_t *pPortAOutRed = (uint32_t*)0x40020004;
	 // enabale rcc port A
	 *pClkCtrRed |= (1<<0);
	 // mode of the IO pin out phut
	 *pPortAModeRed &= ~(1<<6);
	 *pPortAModeRed &= ~(1<<7);
	 *pPortAModeRed |=  (1<<6);
	 // set pa3 low
	 *pPortAOutRed |= (1<<7);
	 while(1)
	 {




	 }
}
