/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 *note optimi sẽ đc set tho từng lv nên khi set sẽ tối ưu khi có biến thay đổi nên dùng volatile để optimi k
 *ảnh hưỡng dẫn đến lỗi k mong muốn.
 ******************************************************************************
 */

#include <stdint.h>
#define RAM_ADDRESS 0X20000000;
volatile int u32CheckingVolatile = 0; // khi set optimi co biến volatile thì sẽ k optimi biến đc code volatile
int Dem = 0;

int main(void)
{
	while(1)
	{
	u32CheckingVolatile = *(int*)RAM_ADDRESS;
	Dem ++;
		if(u32CheckingVolatile != 0)
		{
			break;
		}
	}
	Dem = 100;
	return 0;
}
