/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

int main(void)
{
    RCC_AHB1ENR volatile *const pClkCtrlReg   = (RCC_AHB1ENR*) 0x40023830;
    GPIOx_MODER volatile *const pPortDModeRed = (GPIOx_MODER*) 0x40020C00;
    GPIOX_ODR   volatile *const pPortDOutRed  = (GPIOX_ODR*)   0x40020C14;
    // enable portD
    pClkCtrlReg   ->GPIOD_EN = 1;
    // chonj che do model;
    pPortDModeRed ->pin_12 = 1;
    // set pin_12 high
    pPortDOutRed  -> pin_12 = 1;
    // 10 model
    pPortDModeRed ->pin_12 = 0;
    pPortDModeRed ->pin_12 = 3;
    while (1)
    {

    }


}
