/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
void delay (void)
{
	for(uint32_t i= 0; i<300000; i++);
}
int main(void)
{
    volatile *const pClkCtrlReg   = (uint32_t*) 0x40023830;
    volatile *const pPortDModeRed = (uint32_t*) 0x40020C00;
    volatile *const pPortDOutRed  = (uint32_t*) 0x40020C14;
    volatile *const pPortDInRed   = (uint32_t*) 0x40020C10;
    volatile *const pPortDPUPDR   = (uint32_t*) 0x40020C0C;
    // enable portD
    *pClkCtrlReg |= (1<<3);
    // chonj che do model out put pin 0-3
    *pPortDModeRed &=~( 0xFF);
    *pPortDModeRed |= 0x55;
    // input pin 4-7
    *pPortDModeRed &= ~(0xFF<<8);
    // chế độ đếm lên (pull up)
    *pPortDPUPDR |= (0x55<<8);
    while(1) {
    // make all row HIGH
    *pPortDOutRed |= (0xF);
    // r1 low
    *pPortDOutRed &= ~(1<<0);
    if (!(*pPortDInRed &= ~(1<<4)))
    {
    	delay();
    	printf("1\n");
    }
    if (!(*pPortDInRed &= ~(1<<5)))
        {
    		delay();
        	printf("2\n");
        }
    if (!(*pPortDInRed &= ~(1<<6)))
        {
    		delay();
        	printf("3\n");
        }
    if (!(*pPortDInRed &= ~(1<<7)))
        {
    		delay();
        	printf("A\n");
        }
    // make all row HIGH
      *pPortDOutRed |= (0xF);
      // r2 low
      *pPortDOutRed &= ~(1<<1);
      if (!(*pPortDInRed &= ~(1<<4)))
      {
      	delay();
      	printf("4\n");
      }
      if (!(*pPortDInRed &= ~(1<<5)))
          {
      		delay();
          	printf("5\n");
          }
      if (!(*pPortDInRed &= ~(1<<6)))
          {
      		delay();
          	printf("6\n");
          }
      if (!(*pPortDInRed &= ~(1<<7)))
          {
      		delay();
          	printf("b\n");
          }
      // make all row HIGH
        *pPortDOutRed |= (0xF);
        // r3 low
        *pPortDOutRed &= ~(1<<2);
        if (!(*pPortDInRed &= ~(1<<4)))
        {
        	delay();
        	printf("7\n");
        }
        if (!(*pPortDInRed &= ~(1<<5)))
            {
        		delay();
            	printf("8\n");
            }
        if (!(*pPortDInRed &= ~(1<<6)))
            {
        		delay();
            	printf("9\n");
            }
        if (!(*pPortDInRed &= ~(1<<7)))
            {
        		delay();
            	printf("C\n");
            }
        // make all row HIGH
          *pPortDOutRed |= (0xF);
          // r4 low
          *pPortDOutRed &= ~(1<<3);
          if (!(*pPortDInRed &= ~(1<<4)))
          {
          	delay();
          	printf("*\n");
          }
          if (!(*pPortDInRed &= ~(1<<5)))
              {
          		delay();
              	printf("0\n");
              }
          if (!(*pPortDInRed &= ~(1<<6)))
              {
          		delay();
              	printf("#\n");
              }
          if (!(*pPortDInRed &= ~(1<<7)))
              {
          		delay();
              	printf("D\n");
              }
    }


}
